Cut copy paste
PolicyStat/ckeditor-plugin-autoid-headings pull request #4
Opened 2016-09-22 14:14 UTC by sbaughman

This adds handling of a variety of heading-id integrity issues that can result from cut/paste and copy/paste scenarios.

It takes advantage of the fact that the `paste` event allows the pasted data to be intercepted and modified just before being inserted on the page.  The paste data is parsed and searched for headings.  If there are headings, it checks for id duplication between any copied headings and headings already on the page.  If a duplicate is found, it chooses an appropriate way to resolve the duplication based on various attributes of the two headings.

2016-09-23 20:07 UTC, caffodian commented on tests/paste_events/_helpers/pasting.js
> +function assertPasteEvent( editor, eventData, expected, message, async ) {
There is a crazy amount of special case handling in here!

2016-09-23 20:10 UTC, caffodian commented on tests/paste_events/_helpers/pasting.js
> +		evt.cancel(); // Cancel for performance reason - we don't need insertion happen.
because we just want to assert the data that goes into the handler, not the actual editor content?

2016-09-23 20:10 UTC, caffodian commented on tests/paste_events/_helpers/pasting.js
> +}
Am i crazy, or does this entire file somehow use 5-space tabs?  Or something else is weird.

2016-09-23 20:11 UTC, caffodian commented on tests/paste_events/_helpers/pasting.js
> +	var	nativeData = bender.tools.mockNativeDataTransfer();
Very odd spacing

2016-09-23 20:12 UTC, caffodian commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
Why can't you just set the selection to `headingWithId + '<p>^</p>'` ?

2016-09-23 20:14 UTC, caffodian commented on tests/paste_events/paste_events.js
> +      wait();
bleh, I think bender has a promise addon, but it's not usually used with ckeditor tests.  The more I see things like this, the more I feel like investigating it.  (the reverse reading)

2016-09-23 20:14 UTC, caffodian commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
same deal for selection setting

2016-09-23 20:14 UTC, caffodian requested changes
Looks pretty good, minor changes to consider.

2016-09-23 20:16 UTC, sbaughman commented on tests/paste_events/paste_events.js
> +      wait();
yeah that would be really nice

2016-09-23 20:17 UTC, sbaughman commented on tests/paste_events/_helpers/pasting.js
> +function assertPasteEvent( editor, eventData, expected, message, async ) {
so this file is actually a helper from the clipboard plugin.  I tried symlinking it, but I couldn't get it to work, so I just copy / pasted

2016-09-23 20:18 UTC, sbaughman commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
I tried that, and for some reason when I did it that way it stripped the heading tags and pasted into the paragraph block.

2016-09-23 20:20 UTC, caffodian commented on tests/paste_events/_helpers/pasting.js
> +function assertPasteEvent( editor, eventData, expected, message, async ) {
Hmm.  ok, don't bother with the spacing stuff, but maybe just add a comment with the original source path.

2016-09-23 20:21 UTC, caffodian commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
That is strange.

Can you verify what the HTML looks like, after you press enter?

2016-09-23 20:22 UTC, caffodian commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
I would expect that having the original html you had, and adding enter, would just create a `<p>` (possibly with an nbsp inside) and put the cursor inside.

2016-09-23 20:23 UTC, caffodian commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
If pressing enter actually does something else...that is weiiiiiirrrd.

2016-09-23 21:57 UTC, sbaughman commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
no it definitely creates a p tag.  I don't know why it works differently, but it does

2016-09-27 17:19 UTC, sbaughman commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
Just tried this again today.  Thought maybe I was crazy.  Still doesn't work the way you'd expect

2016-09-27 17:22 UTC, caffodian commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
What does getData look like after you make it press enter?

2016-09-27 17:28 UTC, sbaughman commented on tests/paste_events/_helpers/pasting.js
> +function assertPasteEvent( editor, eventData, expected, message, async ) {
Added attribution

2016-09-27 18:55 UTC, sbaughman commented on tests/paste_events/paste_events.js
> +      // hit enter key to prevent pasting text in same heading element
`<h1 id="12345">This is a heading</h1><p>&nbsp;</p>`

2016-09-27 20:05 UTC, caffodian approved these changes
looks good to me now.  I'm still super curious about that enter vs. setting initial selection, but the test seems to reasonably cover the cut & paste case.

2016-09-27 20:05 UTC, merged